#!/bin/sh
#
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

package="openmediavault-$3"

sfref=$(omv_config_get "//services/developer/sharedfolderref")
sfpath=$(omv_get_sharedfolder_path "${sfref}")
developer="OpenMediaVault-Plugin-Developers"

echo ${package}

if [ ! -d "${sfpath}${package}" ]; then
    cd ${sfpath}
    git clone https://github.com/${developer}/${package}.git
fi

cd ${sfpath}${package}

case $2 in
    update)
        git pull
        git status
    ;;

    build)
        fakeroot debian/rules clean binary
    ;;

    *)
    ;;
esac

exit 0
