#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2014-2015 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        SERVICE_XPATH_NAME="developer"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}" ""
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/sharedfolderref"; then
            omv_config_add_element "${SERVICE_XPATH}" "sharedfolderref" ""
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/owner"; then
            omv_config_add_element "${SERVICE_XPATH}" "owner" ""
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/gitname"; then
            omv_config_add_element "${SERVICE_XPATH}" "gitname" ""
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/gitemail"; then
            omv_config_add_element "${SERVICE_XPATH}" "gitemail" ""
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/txhostname"; then
            omv_config_add_element "${SERVICE_XPATH}" "txhostname" "https://www.transifex.com"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/txpassword"; then
            omv_config_add_element "${SERVICE_XPATH}" "txpassword" ""
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/txtoken"; then
            omv_config_add_element "${SERVICE_XPATH}" "txtoken" ""
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/txusername"; then
            omv_config_add_element "${SERVICE_XPATH}" "txusername" ""
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/locations"; then
            omv_config_add_element "${SERVICE_XPATH}" "locations"
        fi

        pip install transifex-client || :

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
