version: "1.0"
type: component
data:
  name: omv-services-developer-settings-form-page
  type: formPage
  config:
    request:
      service: Developer
      get:
        method: getSettings
      post:
        method: setSettings
    fields:
      - type: divider
        title: _("Settings")
      - type: sharedFolderSelect
        name: sharedfolderref
        label: _("Shared Folder")
      - type: textInput
        name: owner
        label: _("Owner")
        value: "nobody"
      - type: divider
        title: _("git config")
      - type: textInput
        name: gitname
        label: _("Name")
        value: ""
      - type: textInput
        name: gitemail
        label: _("Email")
        value: ""
      - type: divider
        title: _("Github config")
      - type: textInput
        name: ghusername
        label: _("Username")
        value: ""
      - type: passwordInput
        name: ghpassword
        label: _("Password")
        value: ""
      - type: divider
        title: _("Transifex config")
      - type: textInput
        name: txhostname
        label: _("Hostname")
        value: ""
      - type: passwordInput
        name: txpassword
        label: _("Password")
        value: ""
      - type: passwordInput
        name: txtoken
        label: _("Token")
        value: ""
      - type: textInput
        name: txusername
        label: _("Username")
        value: ""
      - type: divider
        title: _("gpg config")
      - type: passwordInput
        name: btgpgpass
        label: _("GPG-key passphrase")
        value: ""
      - type: hidden
        name: rootfsref
        label: _("Root ref")
        value: "79684322-3eac-11ea-a974-63a080abab18"
      - type: folderBrowser
        name: reldirpath
        label: _("path")
        value: '/{{ reldirpath }}'
        dirType: mntent
        dirRefIdField: rootfsref
    buttons:
      - template: submit
      - template: cancel
        execute:
          type: url
          url: "/services/developer"
      - text: _('Create git config')
        execute:
          type: request
          request:
            service: Developer
            method: createConfig
            params:
              command: "git"
            task: false
            progressMessage: _('Creating git config ...')
      - text: _('Create Github .netrc')
        execute:
          type: request
          request:
            service: Developer
            method: createConfig
            params:
              command: "gh"
            task: false
            progressMessage: _('Creating Github .netrc ...')
      - text: _('Create Transifex configs')
        execute:
          type: request
          request:
            service: Developer
            method: createConfig
            params:
              command: "tx"
            task: false
            progressMessage: _('Creating Transifex configs ...')
      - text: _('Update OMV')
        execute:
          type: request
          request:
            service: Developer
            method: doOmvGit
            task: false
            progressMessage: _('Updating OMV from git ...')
